export const siteConfig = {
  name: 'UGESM',
  description: 'Union Générale des Étudiants et Stagiaires Sénégalais au Maroc',
  url: 'https://ugesm.org',
  ogImage: '/logo.png',
  links: {
    twitter: 'https://twitter.com/ugesmc',
    instagram: 'https://www.instagram.com/ugesmrabat/',
  },
  keywords: [
    'UGESM',
    'étudiants sénégalais au maroc',
    'Maroc',
    'études au Maroc',
    'communauté estudiantine',
    'association étudiante',
    'Sénégal',
    'enseignement supérieur',
    'Comment étudier au Maroc en tant qu\'étudiant sénégalais',
    'Bourses d\'études pour étudiants sénégalais au Maroc',
    'Universités marocaines populaires auprès des étudiants sénégalais',
'Coût de la vie pour un étudiant sénégalais au Maroc',
'Procédure d\'inscription universitaire au Maroc pour Sénégalais',
'Communauté des étudiants sénégalais au Maroc',
'Trouver un logement étudiant au Maroc',
'Vie culturelle et intégration des Sénégalais au Maroc',
'Les défis des étudiants sénégalais au Maroc',
'Stages et emplois pour étudiants sénégalais au Maroc',
'Partenariats académiques entre le Sénégal et le Maroc',
'Réseau professionnel pour Sénégalais diplômés au Maroc',
'Perspectives après des études au Maroc pour les Sénégalais',
'Astuces pour bien gérer son budget étudiant au Maroc',
'Guide pour obtenir un visa étudiant marocain depuis le Sénégal',
'Meilleurs quartiers pour vivre en tant qu\'étudiant à Marrakech, Casablanca, Rabat',
'Accès aux soins médicaux pour étudiants sénégalais au Maroc',
'Comment renouveler son titre de séjour étudiant au Maroc',
'Groupes Facebook ou WhatsApp pour étudiants sénégalais au Maroc',
'Associations étudiantes africaines au Maroc',
'Témoignages d\'étudiants sénégalais vivant au Maroc',
'Adaptation au mode de vie marocain en tant qu\'étudiant sénégalais',
'Célébrations religieuses au Maroc pour les étudiants musulmans sénégalais',
'Transport en commun pour étudiants à Marrakech et autres villes',
'Découvrir le Maroc en tant qu\'étudiant sénégalais',
'Histoire et missions de l\'UGESM',
'Contacts UGESM pour les nouveaux étudiants sénégalais au Maroc',
'Calendrier des événements organisés par l\'UGESM',
'UGESM, soutien académique et social pour les étudiants sénégalais',
'Rôle de l\'UGESM dans l\'intégration des Sénégalais au Maroc',
'UGESM, opportunités pour les nouveaux arrivants',
'Histoire et missions de l\'UGESM',
'Contacts UGESM pour les nouveaux étudiants sénégalais au Maroc',
'Calendrier des événements organisés par l\'UGESM',
'UGESM, soutien académique et social pour les étudiants sénégalais',
'Rôle de l\'UGESM dans l\'intégration des Sénégalais au Maroc',
'UGESM, opportunités pour les nouveaux arrivants',
'Comment étudier au Maroc en tant qu\'étudiant sénégalais',
'Bourses d\'études pour étudiants sénégalais au Maroc',
'Universités marocaines populaires auprès des étudiants sénégalais',
'Coût de la vie pour un étudiant sénégalais au Maroc',
'Procédure d\'inscription universitaire au Maroc pour Sénégalais',
'Communauté des étudiants sénégalais au Maroc',
'Trouver un logement étudiant au Maroc',
'Vie culturelle et intégration des Sénégalais au Maroc',
'Les défis des étudiants sénégalais au Maroc',
'Stages et emplois pour étudiants sénégalais au Maroc',
'Partenariats académiques entre le Sénégal et le Maroc',
'Réseau professionnel pour Sénégalais diplômés au Maroc',
'Perspectives après des études au Maroc pour les Sénégalais',
'Astuces pour bien gérer son budget étudiant au Maroc',
'Guide pour obtenir un visa étudiant marocain depuis le Sénégal',
'Meilleurs quartiers pour vivre en tant qu\'étudiant à Marrakech, Casablanca, Rabat',
'Accès aux soins médicaux pour étudiants sénégalais au Maroc',
'Comment renouveler son titre de séjour étudiant au Maroc',
'Groupes Facebook ou WhatsApp pour étudiants sénégalais au Maroc',
'Associations étudiantes africaines au Maroc',
'Témoignages d\'étudiants sénégalais vivant au Maroc',
'Adaptation au mode de vie marocain en tant qu\'étudiant sénégalais',
'Célébrations religieuses au Maroc pour les étudiants musulmans sénégalais',
'Transport en commun pour étudiants à Marrakech et autres villes',
'Découvrir le Maroc en tant qu\'étudiant sénégalais',
'Meilleurs plans pour économiser en tant qu\'étudiant au Maroc',
'Top restaurants africains fréquentés par les étudiants sénégalais au Maroc',
'Comment gérer la nostalgie en tant qu\'étudiant sénégalais à l\'étranger',
'Réunions et rencontres entre étudiants sénégalais au Maroc',
'Impact des traditions marocaines sur les étudiants sénégalais',
'Programmes d\'échange Sénégal-Maroc pour étudiants',
'Rôle des consulats sénégalais dans la vie des étudiants au Maroc',
'Clubs étudiants pour Sénégalais au Maroc',
'Comment organiser ses études et loisirs au Maroc',
'Les meilleures bibliothèques pour étudiants à Rabat, Casablanca, et Marrakech',
'Comparaison entre le système éducatif marocain et sénégalais',
'Témoignages de réussite d\'étudiants sénégalais au Maroc',
'Outils numériques pour étudiants sénégalais au Maroc',
'Fêtes nationales marocaines et leur impact sur les étudiants étrangers',
'Programme de volontariat pour étudiants au Maroc',
'Étudier la médecine au Maroc en tant qu\'étudiant sénégalais',
'Les meilleures écoles d\'ingénieurs pour Sénégalais au Maroc',
'Équivalence des diplômes sénégalais au Maroc',
'Frais de scolarité pour étudiants étrangers au Maroc',
'Préparer un concours au Maroc en tant qu\'étudiant sénégalais',
'Trouver des colocataires sénégalais au Maroc',
'Opportunités de stage au Maroc pour étudiants étrangers',
'Associations sénégalaises présentes dans les villes marocaines',
'Villes marocaines les plus accueillantes pour les Sénégalais',
'Droits et devoirs des étudiants étrangers au Maroc',
'Activités culturelles et sportives pour étudiants sénégalais au Maroc',
'Partage d\'expériences entre étudiants africains au Maroc',
'Créer son entreprise au Maroc après ses études',
'Opportunités pour les étudiants sénégalais dans les écoles privées marocaines',
'Comment les étudiants sénégalais célèbrent leurs fêtes au Maroc',
'Vie nocturne pour les étudiants sénégalais au Maroc',
'Trouver un mentor académique au Maroc en tant qu\'étudiant sénégalais',
'Les forums étudiants pour Sénégalais au Maroc',
'Préparation au marché du travail marocain pour Sénégalais',
'Impact des coutumes marocaines sur la vie quotidienne des étudiants étrangers',
'Les opportunités de volontariat pour les étudiants sénégalais au Maroc',
'Les démarches pour ouvrir un compte bancaire étudiant au Maroc',
'Astuces pour éviter les pièges en tant qu’étudiant étranger au Maroc',
'Les salons étudiants pour étrangers organisés au Maroc',
'Les réunions annuelles de l\'UGESM pour les étudiants sénégalais',
'UGESM, une ressource pour résoudre les conflits entre étudiants sénégalais',
'Comment l\'UGESM soutient les nouveaux arrivants au Maroc',
'La place de l\'UGESM dans la promotion des cultures sénégalaise et marocaine',
'Groupes de travail académiques organisés par l\'UGESM',
'Programmes de mentorat interuniversitaires via l\'UGESM',
'UGESM et l\'organisation des journées culturelles sénégalaises au Maroc',
'Soutien juridique et administratif pour les étudiants sénégalais par l\'UGESM',
'Programmes de retour au Sénégal soutenus par l\'UGESM',
'UGESM et la promotion des valeurs africaines au Maroc',
'Comment financer ses études au Maroc',
'Opportunités pour Sénégalais dans les centres de formation professionnelle marocains',
'Les initiatives de la diaspora sénégalaise au Maroc',
'Collaboration entre étudiants sénégalais et marocains dans des projets communs',
'Impact des accords bilatéraux sur les études des Sénégalais au Maroc',
'Événements interafricains organisés dans les universités marocaines',
'Impact des langues (français, arabe) sur la réussite des étudiants sénégalais au Maroc',
'Meilleurs conseils pour réussir son intégration sociale au Maroc',
'Les meilleurs programmes de master au Maroc pour étudiants sénégalais',
'Étudier en français ou en arabe au Maroc : ce qu\'il faut savoir',
'Les écoles de commerce marocaines pour les Sénégalais',
'Où acheter des produits sénégalais au Maroc',
'Meilleurs plans pour voyager au Maroc avec un budget étudiant',
'Comment trouver un emploi étudiant au Maroc',
'Opportunités d\'apprentissage en ligne pour étudiants étrangers au Maroc',
'Les partenariats éducatifs entre universités marocaines et sénégalaises',
'Calendrier académique marocain : différences avec le Sénégal',
'Trouver un stage d\'été au Maroc en tant qu\'étudiant sénégalais',
'Impact de la culture culinaire marocaine sur les étudiants sénégalais',
'Comparaison des options de transport pour étudiants au Maroc',
'Les aides financières disponibles pour étudiants étrangers au Maroc',
'La gastronomie marocaine pour les étudiants sénégalais',
'Comment s\'intégrer dans les groupes d\'étudiants marocains',
'Les villes universitaires les plus abordables au Maroc',
'Faire des études en médecine dentaire au Maroc pour Sénégalais',
'Les traditions marocaines expliquées aux étudiants étrangers',
'Programmes de leadership pour étudiants au Maroc',
'Les opportunités d’études dans les régions rurales du Maroc',
'Projets humanitaires soutenus par l\'UGESM',
'L\'UGESM face aux défis de la vie étudiante au Maroc',
'Les anciens membres de l\'UGESM et leurs réussites',
'UGESM : organiser un événement culturel au Maroc',
'Comment devenir un membre actif de l\'UGESM',
'Les programmes de sensibilisation de l\'UGESM pour les nouveaux étudiants',
'Activités de l\'UGESM pendant le Ramadan',
'UGESM et les rencontres interafricaines au Maroc',
'Astuces pour profiter pleinement des activités organisées par l\'UGESM',
'Comment l\'UGESM aide les étudiants sénégalais à réussir leurs études',
'Le système éducatif marocain expliqué aux Sénégalais',
'Quelles compétences développer en étudiant au Maroc',
'Comment gérer le mal du pays en tant qu’étudiant sénégalais',
'Le Maroc vu à travers les yeux d’un étudiant africain',
'Le rôle des consulats sénégalais dans la vie estudiantine au Maroc',
'Les festivals culturels marocains à ne pas manquer',
'Sénégalais au Maroc : comment trouver un réseau d’entraide',
'Les défis linguistiques pour les étudiants sénégalais au Maroc',
'Les opportunités d’apprentissage technique pour Sénégalais au Maroc',
'Comment équilibrer études et loisirs au Maroc',
'Les traditions africaines dans les campus marocains',
'Organiser des réunions entre Sénégalais et Marocains pour des projets communs',
'Découverte des régions marocaines pour étudiants étrangers',
'Comment les universités marocaines célèbrent la diversité culturelle',
'Les ressources en ligne pour les étudiants sénégalais au Maroc',
'Les démarches pour obtenir un permis de travail au Maroc pour étudiants sénégalais',
'Étudier l’agriculture au Maroc en tant qu’étudiant sénégalais',
'Trouver des opportunités de bénévolat pour étudiants sénégalais au Maroc',
'La gestion des loisirs pour étudiants étrangers au Maroc',
'L’impact des études au Maroc sur la carrière professionnelle des Sénégalais',
'Les meilleures formations en marketing et communication au Maroc pour étudiants sénégalais',
'Les meilleures options de transport pour étudiants étrangers au Maroc',
'Les étudiants sénégalais au Maroc : défis et opportunités',
'Comment créer un réseau professionnel au Maroc en tant qu’étudiant sénégalais',
'Les différences entre le système universitaire marocain et sénégalais',
'Vivre à Rabat en tant qu’étudiant sénégalais',
'Les opportunités d’échange entre le Maroc et le Sénégal pour étudiants',
'Trouver un stage en droit au Maroc pour étudiants sénégalais',
'Opportunités de partenariat universitaire entre les écoles marocaines et sénégalaises',
'Les universités marocaines offrant des cours en anglais pour étudiants sénégalais',
'Célébrations traditionnelles marocaines pour étudiants étrangers',
'Opportunités pour les étudiants sénégalais dans le secteur du tourisme au Maroc',
'Les impacts des voyages interrégionaux pour les étudiants sénégalais au Maroc',
'La solidarité entre étudiants africains au Maroc',
'Les services d’aide à l’orientation académique offerts par l’UGESM',
'Comment l’UGESM soutient l’intégration des étudiants sénégalais dans la société marocaine',
'Les programmes d’échanges inter-étudiants au sein de l’UGESM',
'UGESM : un acteur clé dans l’organisation des événements communautaires sénégalais au Maroc',
'Témoignages d’étudiants ayant participé à des projets de l’UGESM',
'Le rôle de l’UGESM dans la défense des droits des étudiants sénégalais au Maroc',
'UGESM : réseau de soutien aux étudiants sénégalais en difficulté',
'Les rencontres sportives et culturelles organisées par l’UGESM pour les étudiants sénégalais',
'Programmes de mentorat universitaire organisés par l’UGESM',
'Développement des compétences professionnelles des étudiants sénégalais grâce à l’UGESM',
'Comment réussir ses études en ingénierie au Maroc pour étudiants sénégalais',
'Les meilleures pratiques pour éviter les arnaques en tant qu’étudiant étranger au Maroc',
'Les différents types de bourses offertes aux étudiants sénégalais au Maroc',
'Trouver des opportunités de voyage à bas prix pour étudiants au Maroc',
'Vivre dans une résidence universitaire au Maroc pour étudiants sénégalais',
'Organiser un événement de solidarité sénégalaise au Maroc',
'Comment développer ses projets de recherche au Maroc en tant qu’étudiant sénégalais',
'Les meilleurs moyens de se préparer à la transition après des études au Maroc',
'Les événements inter-universités entre étudiants sénégalais et marocains',
'Trouver un emploi à temps partiel pour étudiants sénégalais au Maroc',
'Les différents types de logements étudiants au Maroc et comment les trouver',
'Réussir dans une école de commerce marocaine en tant qu’étudiant sénégalais',
'Les spécificités des études en sciences sociales au Maroc pour les Sénégalais',
'Comment gérer un projet de fin d’études au Maroc pour un étudiant sénégalais',
'L’importance de la pratique linguistique en arabe et en français pour les étudiants sénégalais au Maroc',
'stagiaires sénégalais'
  ]
}
